### ISSUE TITLE
User management user story

### ISSUE THREAD

**Issue by kranthi0099** [sankar-vema/py-skelton#10]
Only the Admin has every right to do the user management.
In user management the admin can see the list of user’s & their status details.
Only the admin has rights to lock, unlock & delete the users.

The user page consists of gird menu where every user is visible to the admin & each user will have options like "edit", "lock", "unlock" & "deactivate"

This page also consists of adding a user one by one & importing bulk user from a CSV or excel file.

**Comment by SujaAniyan** [comment]
Admin menu is appearing for all users. Users who are not Admins are able to lock and unlock.
