### ISSUE TITLE
Login Page user story

### ISSUE THREAD

**Issue by kranthi0099** [sankar-vema/py-skelton#4]
1. The login page is used to login/ sign into the application.
2. It consists of text fields for entering username & password, one login button, registration & forgot password links.
3. The login page will validate the details given by the user & if the given credentials satisfied the dashboard page will be presented for the user.
4. If in case the given user details doesn’t match, an error message will be displayed on the same page.
5. Once the user login, session will be activated for that user & it will remain active as long as the user is active. If the user is inactive for a specific amount of time the sessions will be destroyed & we will force the user to re-login once again to continue with is work.
6. When a user tries to access any page of the application without login, we’ll redirect the user to the login page.

**Comment by SujaAniyan** [comment]
"When a user tries to access any page of the application without logging we’ll force him to login to the application by using the login page." feature not working. Need to verify session timeout.

**Comment by kranthi0099** [comment]
user story edited.
