### ISSUE TITLE
Password Hashing user story

### ISSUE THREAD

**Issue by kranthi0099** [sankar-vema/py-skelton#5]
The passwords will be stored in the DB through one-way encryption.
one-way encryption, or a one-way hash function, is designed in such a way that it is hard to reverse the process

When the user logins, an encryption key will be generated from the password entered & it will be validated against the encrypted password stored in the DB.

If both the encrypted keys matches the user can login to the application, Or else an error message will be shown like “Unable to login with provided credentials”.

**Comment by SujaAniyan** [comment]
Currently different error message is getting displayed - "Unable to login with provided credentials"

**Comment by kranthi0099** [comment]
user story edited.
