### ISSUE TITLE
Header & Footer User story

### ISSUE THREAD

**Issue by kranthi0099** [sankar-vema/py-skelton#7]
The header consists of a nav-bar which will have the Project name (or) logo on the left hand side & page navigation links on the right hand side. 

If the user is logged in the nav-bar consists of user profile menu on the right most corner.

The nav-bar will be display only "Home" & "About Us" links when the user is not logged in.
once the use logins the nav-bar will have additional links including "About Us" & "Home"

The footer will have the license & copy rights information of the application.

**Comment by SujaAniyan** [comment]
Login and Register links not appearing

**Comment by guptaaman2011** [comment]
user story edited
